package com.kingofthebeasts.app.ui

import android.annotation.SuppressLint
import android.content.Context
import androidx.annotation.DrawableRes
import com.kingofthebeasts.app.R

/**
 * Card art lives in res/drawable-nodpi/art_<card id>.webp (generated by tools/art).
 * Dropping in a real painting with the same name replaces the generated one.
 */
object CardArt {
    private val cache = HashMap<String, Int>()

    @SuppressLint("DiscouragedApi")
    @DrawableRes
    fun res(context: Context, cardId: String): Int = cache.getOrPut(cardId) {
        context.resources.getIdentifier("art_$cardId", "drawable", context.packageName)
            .takeIf { it != 0 } ?: R.drawable.paper_background
    }
}
